### ISSUE TITLE
ConvTranspose Layer

### ISSUE THREAD

**Issue by SauravMaheshkar** [google/trax#1065]
It would be nice to have a **Transpose Convolution Layer** added to the ```trax.layers.convolution``` class.

**Comment by lukaszkaiser** [comment]
Agreed! If anyone's willing to send a PR, that'd be great!

**Comment by SauravMaheshkar** [comment]
I've been working on PR #1098.

**Comment by SauravMaheshkar** [comment]
My PR #1098 was merged. Therefore, closing this Issue.
