### ISSUE TITLE
Question, will trax support ONNX, Java, Javascript, or C++?

### ISSUE THREAD

**Issue by JonathanSum** [google/trax#1128]
### Description
Question, will Trax support ONNX, Java, Javascript, or C++?
...

### Environment information
Window/Linux
```
OS: <your answer here>

$ pip freeze | grep trax
# your output here

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
I think you can use Trax now with C++ and Javascript - just go through the TensorFlow backend as described here:
https://trax-ml.readthedocs.io/en/latest/notebooks/tf_numpy_and_keras.html

That will give you a SavedModel which can be run from JavaScript or C++ without a python interpreter, and I think it can be converted to ONNX too, though I'm not sure. If there'a a better way, please let us know!
