### ISSUE TITLE
Trax Quick Intro error AttributeError: module 'trax.layers' has no attribute 'WeightedCategoryCrossEntropy'

### ISSUE THREAD

**Issue by wee-analyze** [google/trax#1285]
### Description

The Trax Quick Intro colab has an error in the Supervised Training section that `AttributeError: module 'trax.layers' has no attribute 'WeightedCategoryCrossEntropy'`

**Comment by ricottablue** [comment]
> ### Description
> The Trax Quick Intro colab has an error in the Supervised Training section that `AttributeError: module 'trax.layers' has no attribute 'WeightedCategoryCrossEntropy'`

[https://github.com/google/trax/issues/1277#issuecomment-740017511](url)

**Comment by wee-analyze** [comment]
> > ### Description
> > The Trax Quick Intro colab has an error in the Supervised Training section that `AttributeError: module 'trax.layers' has no attribute 'WeightedCategoryCrossEntropy'`
> 
> [https://github.com/google/trax/issues/1277#issuecomment-740017511](url)



> > ### Description
> > The Trax Quick Intro colab has an error in the Supervised Training section that `AttributeError: module 'trax.layers' has no attribute 'WeightedCategoryCrossEntropy'`
> 
> [https://github.com/google/trax/issues/1277#issuecomment-740017511](url)

Nothing opens when I click the link. Is it the wrong link?

**Comment by thoo** [comment]
Here is the working link. Basically, you need to install `Trax` from master branch to get it working. 

https://github.com/google/trax/issues/1277#issuecomment-740017511
