### ISSUE TITLE
NER_using_Reformer(from examples): How do i predict my own data?

### ISSUE THREAD

**Issue by ricottablue** [google/trax#1313]
Hello,

I'm trying to predict my own data following the "NER_using_Reformer.ipynb" but i can't.

![image](https://user-images.githubusercontent.com/44533299/102364288-90bf8380-3fb6-11eb-952e-79115e6da84e.png)

Someone can explain me how do that?

Thanks.

**Comment by ritesh-hitech** [comment]
I am having the same problem. Did you find an answer?
