### ISSUE TITLE
Build my own vocabulary

### ISSUE THREAD

**Issue by ngoquanghuy99** [google/trax#1338]
How can i build my own vocab based on my own data instead of importing your vocab file ('ende_32k.subword' for example)?

**Comment by afrozenator** [comment]
PTAL at https://github.com/google/trax/blob/master/trax/data/text_encoder_build_subword.py

**Comment by fractaldragonflies** [comment]
I don't understand this answer.  But the original requester seem gave a thumb up, so I guess he is satisfied. Now if I can just understand it.
