### ISSUE TITLE
Not able to install trax correctly on my machine

### ISSUE THREAD

**Issue by ishan42d** [google/trax#1345]
### Description

I am not able to install trax correctly on my machine. I am using MAC-OS currently and installing the trax at the root level like any other library. I m using the following code:

import os
import numpy as np

!pip install -q -U trax
import trax

# Error logs:
I am facing the following error :
ValueError: A configurable matching 'trax.data.tf_inputs.data_streams' already exists.

To allow re-registration of configurables in an interactive environment, use:

    gin.enter_interactive_mode()
How do get rid of it and install the library correctly? 

and If use the below code:
import os
import numpy as np
import tensorflow
import gin
!pip install -q -U trax
import trax
gin.enter_interactive_mode()

I get the following error : 
`~/opt/anaconda3/lib/python3.7/site-packages/trax/data/tf_inputs.py in <module>
    504 
    505 # Makes the function accessible in gin configs, even with all args denylisted.
--> 506 @gin.configurable(denylist=['dataset', 'training'])
    507 def cifar10_no_augmentation_preprocess(dataset, training):
    508   del training

TypeError: configurable() got an unexpected keyword argument 'denylist'`

**What should I do to install it correctly?**

**Comment by ishan42d** [comment]
I was able to install this! Closing this issue! 
!pip install --upgrade -q gin git+https://github.com/google/trax.git@v1.2.3

**Comment by ZeynabR** [comment]
Hey @ishan42d. I have the same problem but the link that you mentioned doesn't work. can you help me with that?
