### ISSUE TITLE
Error for Transformer in predict mode

### ISSUE THREAD

**Issue by Arun176** [google/trax#1410]
### Description

Hi, 

I'm getting an error when I try to generate a sample using a transformer in 'predict' mode with the function
trax.supervised.decoding.autoregressive_sample()

If I use the same transformer but in 'train' or 'eval' mode and try to generate a sample, it works and looks like it just returns the first element of the output repeated many times. 

The error that I get when it is run in 'predict' mode is:
ValueError: AssertShape Error. Expected ['.d'], got [(4, 1, 512)] with dict {'d': 512, '.': (1, 1)}. Defined at /usr/local/lib/python3.6/dist-packages/trax/layers/attention.py:440 function output

Could you please help? Have I made a mistake somewhere or is this a bug in trax? The model has been training without problems for more than 12 hours, with the accuracy now around 60%. So it looks like the model works fine, apart from in predict mode. 

Thanks very much. 

Please see below for a simple repro of the error, as well as a Colab notebook for reproducing the issue:

Colab notebook:
https://colab.research.google.com/drive/1ylfsmZJP10byL7dUIS7wAJUHqAlWXaXO?usp=sharing
 
Simple repro:

!pip -q install trax
import numpy as np
import trax   
from trax import layers as tl
from trax.supervised import training
!pip list | grep trax

# Model in predict mode - throws as error.

# Create a Transformer model in predict mode   
modelPredict = trax.models.Transformer(
    input_vocab_size=126,
    d_model=512, d_ff=2048,
    n_heads=8, n_encoder_layers=6, n_decoder_layers=6,
    max_len=8196, mode='predict')

modelPredict.init_from_file("gs://bachchorale_transformer/modelCopy.pkl.gz",
                      weights_only=True)

tokenized = [1,2,3,4]

tokenized = np.expand_dims(tokenized, axis=0)

tokenized_output = trax.supervised.decoding.autoregressive_sample(
    modelPredict, tokenized, temperature=0.0)  # Higher temperature: more diverse results.

# The above gives the following error:
ValueError: AssertShape Error. Expected ['.d'], got [(4, 1, 512)] with dict {'d': 512, '.': (1, 1)}. Defined at /usr/local/lib/python3.6/dist-packages/trax/layers/attention.py:440 function output

# Model in eval mode - this works fine

# Create a Transformer model in eval mode   
modelEval = trax.models.Transformer(
    input_vocab_size=126,
    d_model=512, d_ff=2048,
    n_heads=8, n_encoder_layers=6, n_decoder_layers=6,
    max_len=8196, mode='eval')

modelEval.init_from_file("gs://bachchorale_transformer/modelCopy.pkl.gz",
                      weights_only=True)

tokenized = [1,2,3,4]

tokenized = np.expand_dims(tokenized, axis=0)

tokenized_output = trax.supervised.decoding.autoregressive_sample(
    modelEval, tokenized, temperature=0.0)  # Higher temperature: more diverse results.

print(tokenized_output)

#The above returns the following output
# [[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
#  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
#  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]]

# Model in train mode - this works fine. 
# Create a Transformer model in train mode   
modelTrain = trax.models.Transformer(
    input_vocab_size=126,
    d_model=512, d_ff=2048,
    n_heads=8, n_encoder_layers=6, n_decoder_layers=6,
    max_len=8196, mode='train')

modelTrain.init_from_file("gs://bachchorale_transformer/modelCopy.pkl.gz",
                      weights_only=True)

tokenized = [1,2,3,4]

tokenized = np.expand_dims(tokenized, axis=0)

tokenized_output = trax.supervised.decoding.autoregressive_sample(
    modelTrain, tokenized, temperature=0.0)  # Higher temperature: more diverse results.

print(tokenized_output)

# The above returns the following output. 
#[[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
#  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
#  4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]]

**Comment by elx42** [comment]
Hi,

I have the exact same issue and I'm at bit out of ideas where to look at.  When I run the example given on the repo frontpage (https://github.com/google/trax#1-run-a-pre-trained-transformer), everything works perfectly fine. Using my own trained network: creating a fresh Transformer with required parameters as used for training, and replacing the model.pkl.gz path (exactly as in the example), I have the same issue as described above (for 'predict'):  

ValueError: AssertShape Error. Expected ['.d'], got [(128, 1, 512)] with dict {'d': 512, '.': (1, 1)}.

Looking at the print out of both models (given repo example, and self-trained) they are almost identical (I used different vocab size, and max length - but this is all set correctly).

Any indications, where we could investigate further would be highly appreciated. Thank you!

**Comment by Arun176** [comment]
Hi @elx42, 

I managed to solve this, indeed it is because of the input_signature. 
Apparently when you call init_from_file for a model in predict mode, you need to add input_signature, like this:

model = trax.models.Transformer(
        input_vocab_size=126,
        d_model=512, d_ff=2048,
        n_heads=8, n_encoder_layers=6, n_decoder_layers=6,
        max_len=8192, mode='predict')

shape11 = trax.shapes.ShapeDtype((1, 1), dtype=np.int32)  # Needed in predict mode.
model.init_from_file("<pathToFile>/model.pkl.gz",
                      weights_only=True, input_signature=(shape11,shape11))

Then it worked fine for me. I'm not sure why this isn't needed for the example on the repo. I was confused by that as well. But once you add the input_signature (which is not needed for train and eval modes), it works correctly in predict mode. 

Hope this helps!

**Comment by elx42** [comment]
Thanks @Arun176! Yes, that also seems to solve it for me. Now I need to understand what actually happens in the back. :)
