### ISSUE TITLE
History attribute append not found

### ISSUE THREAD

**Issue by PizBernina** [google/trax#1466]
### Description

Anyone having issues importing `history`? It cannot find the `append` attribute.
### Environment information
OS: <Ubuntu 20.04>

$ pip freeze | grep trax
trax==1.3.7

$ pip freeze | grep tensor
mesh-tensorflow==0.1.18
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-datasets==4.0.1
tensorflow-estimator==2.4.0
tensorflow-gcs-config==2.4.0
tensorflow-hub==0.11.0
tensorflow-metadata==0.27.0
tensorflow-probability==0.12.1
tensorflow-text==2.4.3

$ pip freeze | grep jax
jax==0.2.9
jaxlib==0.1.60+cuda101

$ python -V
Python 3.6.9

### For bugs: reproduction and error logs
# Steps to reproduce:
`from trax.supervised import history`
`history.append('train', 'metrics/accuracy', 1, 0.04)`
# Error logs:
`AttributeError: module 'trax.supervised.history' has no attribute 'append'
`

**Comment by necromuralist** [comment]
If you look in the history.py file there's a class named `History` that has the methods in it, there's no module level `append`. Perhaps if you instantiated the class and then used the method. Something like:

```python
from trax.supervised.history import History
h = History()
h.append('train', 'metrics/accuracy', 1, 0.04)
```

**Comment by PizBernina** [comment]
see comment from @necromuralist
