### ISSUE TITLE
[Question] [Request] Tutorial for implementing TensorBoard

### ISSUE THREAD

**Issue by PizBernina** [google/trax#1467]
Is there a tutorial or similar out there that describes how to implement TensorBoard with Trax? Similar to what exists for Tensorboard with tf or pytorch.

I have noticed there are some files distributed along the trax github account ([callbacks](https://github.com/google/trax/blob/5b08d66a4e69cccbab5868697b207a8b71caa890/trax/supervised/callbacks.py#L58), [history](https://github.com/google/trax/blob/5b08d66a4e69cccbab5868697b207a8b71caa890/trax/supervised/history.py), [jaxboard](https://github.com/google/trax/blob/5b08d66a4e69cccbab5868697b207a8b71caa890/trax/jaxboard.py)) but haven't found any beginner friendly docs.

**Comment by OmarAlsaqa** [comment]
The Trax training loop optimizes training, creates TensorBoard logs and model checkpoints in the output directory for you. you could simply visualize them using the following:

```python
# Load the TensorBoard notebook extension
%load_ext tensorboard

%tensorboard --logdir output_dir
```

if it is not loading properly, and for example your `output_dir` is:

```python
output_dir = '/content/drive/MyDrive/Colab Notebooks/Transformer_FR_pretrained_336'
```
add:
```
%cd '/content/drive/MyDrive/Colab Notebooks/'
```
before:
```
%tensorboard --logdir output_dir
```
and change it to:
```
%tensorboard --logdir Transformer_FR_pretrained_336
```

**Comment by PizBernina** [comment]
Thanks  so much @OmarAlsaqa! the cd line solved my problem!
