### ISSUE TITLE
Add ohter variants of transformers

### ISSUE THREAD

**Issue by behroozazarkhalili** [google/trax#1558]
Could you please add Linfomer, Performer, Longformer, and other transformers' variants to this package?
The PyTorch versions are available here:
https://github.com/lucidrains/x-transformers
https://github.com/lucidrains/transformer-in-transformer
https://github.com/lucidrains/performer-pytorch
https://github.com/lucidrains/nystrom-attention
https://github.com/lucidrains/sinkhorn-transformer
https://github.com/lucidrains/transganformer
...

### Environment information

```
OS: Linux Mint 20

$ pip freeze | grep Trax
trax==1.3.7

$ pip freeze | grep tensor
mesh-tensorflow==0.1.19
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.1
tensorflow==2.4.1
tensorflow-datasets==4.2.0
tensorflow-estimator==2.4.0
tensorflow-hub==0.11.0
tensorflow-metadata==0.29.0
tensorflow-text==2.4.3

$ pip freeze | grep jax
jax==0.2.10
jaxlib==0.1.62

$ python -V
Python 3.8.5
```
```

**Comment by afrozenator** [comment]
Performer's Favor+ and CausalFavor have been implemented - https://github.com/google/trax/blob/3160dec9633bde3c7bb1337aefaf03ba7f23a703/trax/layers/research/sparsity.py#L747-L752

Please feel free to add the others!
