### ISSUE TITLE
why tpu gan not work on a kaggle notebook when using trax 1.3.7?

### ISSUE THREAD

**Issue by quoniammm** [google/trax#1560]
**i run a model of trax version on a kaggle notebook.**

<img width="1054" alt="截屏2021-03-26 下午3 59 23的副本" src="https://user-images.githubusercontent.com/12003094/112600772-90077a80-8e4c-11eb-8b77-a5bd04375def.png">

**the documents of trax said as the below:**

<img width="805" alt="截屏2021-03-26 下午4 02 56" src="https://user-images.githubusercontent.com/12003094/112601017-de1c7e00-8e4c-11eb-95c0-fee89a91361f.png">

**what's the reason of it that the tpu can not work when i trained a model?**

**Comment by afrozenator** [comment]
Can you explain more, it may just have been re-compiling for a different size internally, looks like it did a run and produced the loss at step 1, right?

Feel free to reopen if needed.
