### ISSUE TITLE
the problem of implementing multi-head attention?

### ISSUE THREAD

**Issue by quoniammm** [google/trax#1582]
<img width="803" alt="截屏2021-04-11 下午5 23 07" src="https://user-images.githubusercontent.com/12003094/114298814-c1d63d80-9aea-11eb-817c-86258104e21c.png">

the x in above trax code is Q or K or V, Why is x only rerange and not like in the paper rerange is preceded by a linear transformation.

![IMG_E0431384C47A-1](https://user-images.githubusercontent.com/12003094/114298973-85571180-9aeb-11eb-8506-8293b68ab7d3.jpeg)

why trax didn't use this linear transformation?

**Comment by afrozenator** [comment]
This is just the part where we split into heads, the linear projection is done outside this function, please see - https://github.com/google/trax/blob/e95e435bd221f6605fdc0283c5c1b499e3df8b98/trax/layers/attention.py#L422

**Comment by afrozenator** [comment]
https://github.com/google/trax/blob/e95e435bd221f6605fdc0283c5c1b499e3df8b98/trax/layers/attention.py#L422-L431
