### ISSUE TITLE
[Feature request] Parallel evaluation

### ISSUE THREAD

**Issue by apresta** [google/trax#161]
Right now training and evaluation are interleaved. This means that increasing the eval steps or frequency slows down training.
It would be great to have the option to spawn a separate process for evaluation.

**Comment by lukaszkaiser** [comment]
I agree that this would be interesting, but it's also quite difficult. Where should the new process run, on the same machine or a different one? How should that be configured? So while it'd be nice to have (and certainly great if someone contributes it, hint hint!), I don't think we'll find the time to work on this any time soon. Closing for now, but please re-open when there's activity!
