### ISSUE TITLE
Wrapping up a combinator layer

### ISSUE THREAD

**Issue by aycandv** [google/trax#1681]
### Description

I want to create a simple wrapper class for a combinator such as `tl.Serial`. For example, consider this model:
```
model = tl.Serial(tl.Dense(1) , tl.Dense(1))
```
This `model` can be used/optimized without any problem.

I tried to create a wrapper class like this one:
```
class F(base.Layer):
	def __init__(self):
		self.model = tl.Serial(tl.Dense(1) , tl.Dense(1))
	def forward(self, x):
		return self.model(x)
```

### Question

The problem is that I cannot access the weights of `self.model` through an instance of class `F`. Is there a way to achieve this goal?

**Comment by manifest** [comment]
@aycandv In your example, you forget to implement the [init_weights_and_state](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.base.Layer.init_weights_and_state).

But there is a simpler way to wrap a combinator. You may just create a function:

```python
def F():
    return tl.Serial(
        tl.Dense(1),
        tl.Dense(1),
    )
```

_Note that there is also a [gitter chat](https://gitter.im/trax-ml/community) for community :-)_

**Comment by aycandv** [comment]
Thanks for your answer! 🙂
