### ISSUE TITLE
Proper comparison on real-world applications

### ISSUE THREAD

**Issue by dimeldo** [google/trax#248]
I'd like to see a proper comparison against transformer (GPT-2) on text-generation with the same number of parameters. I'd like to see how it compares against when trained on sequences with the same length, and when Reformer uses a bigger context window.

Thanks a lot for your unique contribution, but substantial empirical and qualitative evidence still lacks.

**Comment by lukaszkaiser** [comment]
This does not feel like a Trax issue but more a comment on the Reformer paper. So while we're certainly looking forward to more experiments with Reformer, closing this here.
