### ISSUE TITLE
Number of inputs Serial.forward error

### ISSUE THREAD

**Issue by rodrigobaron** [google/trax#253]
### Description
Got inputs layer issue testing Resnet50 with cifar10 as toy example:
`ValueError: number of inputs (2) to Serial.forward less than n_in (3)`.

https://gist.github.com/rodrigobaron/e0874af5e8e32b18411fa4bb30e49174
...

### Environment information
Jax==0.1.52
Trax==1.2.2
Tensorflow==1.15.0
```
OS: Linux (Google Colab)
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
Import https://gist.github.com/rodrigobaron/e0874af5e8e32b18411fa4bb30e49174 on Google Colab and run with GPU runtime.
```

```
# Error logs:
LayerError: Exception passing through layer Serial (in _forward_internal):
  layer created in file [...]/trax/supervised/trainer_lib.py, line 674
  layer input shapes: (ShapeDtype{shape:(32, 32, 32, 3), dtype:float32}, ShapeDtype{shape:(32, 10), dtype:float32})

  File [...]/trax/layers/combinators.py, line 59, in forward_with_state
    self._validate_forward_inputs(xs)

  File [...]/trax/layers/combinators.py, line 137, in _validate_forward_inputs
    ' ({})'.format(len(xs), self.n_in))

ValueError: number of inputs (2) to Serial.forward less than n_in (3)
```

**Comment by afrozenator** [comment]
Hi @rodrigobaron - I *think* the problem is that you passed in `has_weights=True` in the `trainer = trax.supervised.Trainer(` declaration, can you check without it and let me know?

If you set this to True, then you have to specify a per example weight as well.

**Comment by rodrigobaron** [comment]
Hoo that's per sample weight, makes sense!
Works @afrozenator, thanks for your help :smile:
