### ISSUE TITLE
Trax advantage vs other framework ?

### ISSUE THREAD

**Issue by tchaton** [google/trax#276]
### Description

Dear people,

What would be the advantage of trax vs tf or Pytorch ?

Best,
T.C

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
Trax can actually run with a TF backend, so it's not one vs the other. We aim to make Trax code easily understandable from first principles, so it can be used as a reference and for clarity.
