### ISSUE TITLE
output_dir = None breaks Trainer

### ISSUE THREAD

**Issue by Yanmarka** [google/trax#299]
### Description
When setting the output_dir argument to None when creating a trax.supervised.Trainer this leads to the reset method not being called (Line 216/217 in in trainer_lib: `if output_dir is not None:
      self.reset(output_dir)`), which breaks the Trainer because the reset method sets the train_stream among other things and a model can't function without the train stream. Surely you would still want to have a train stream even if not writing the model to an output dir? Is there a reason for the if condition in line 216?

### For bugs: reproduction and error logs

```
# Steps to reproduce:
Create a trainer with any model without setting an output_dir.
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
Corrected -- should work on head now.
