### ISSUE TITLE
Training speed of NMT models

### ISSUE THREAD

**Issue by prajdabre** [google/trax#350]
### Description
I modified the ende reformer config to train my own reformer model for a low resource language pair (18000 sentence pairs). Note that I am using GPUs and not TPUs. I found that the reformer encoder-decoder trains very slowly (1 second per batch on a V100). Is this normal? I was under the impression that the reformer trains fast. Am I missing something?
...

### Environment information

```
OS: CentOS

$ pip freeze | grep tensor
mesh-tensorflow==0.1.9
tensor2tensor==1.14.0
tensorboard==1.15.0
tensorflow-datasets==1.3.2
tensorflow-estimator==1.15.1
tensorflow-gan==2.0.0
tensorflow-gpu==1.15.0
tensorflow-hub==0.7.0
tensorflow-metadata==0.21.0
tensorflow-probability==0.7.0


$ pip freeze | grep jax
jax==0.1.57
jaxlib==0.1.37
I have installed the GPU versions of this.

$ python -V
Python 3.6.8

```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```
I run: python -m trax.trainer --config_file=$PWD/trax/configs/reformer_wmt_ende.gin
```
# Error logs:
...
```
N/A

**Comment by lukaszkaiser** [comment]
This feels slow indeed. But just to know the baseline: could you provide the speed of a comparable pytorch/TF model on the same hardware with the same batch size?

**Comment by prajdabre** [comment]
Hello,

On a v100 on similar settings using tensor2tensor, it takes less than 20 seconds per 100 batches or 0.2 seconds per batch. My guess is that, reformer has to recompute activations during backpropagation and this involves an overhead. Another thing is that reformer probably works on TPUs much faster (more compute cores or better addition-subtraction optimizations which reformer relies on). In any case, I would like to know if there is any way to speed things up.

Regards.

**Comment by lukaszkaiser** [comment]
I think that the batches for Reformer may be much larger - so it may take longer per batch, but the difference in speed per token isn't that big? Have you checked what are the exact batch sizes in both cases, do they match?

**Comment by prajdabre** [comment]
Hi,

Now that you mention it, I noticed that the batch sizes are 256 SENTENCES per batch instead of the default 2048 TOKENS in transformer big.

Assuming an average token size of 24 thats 6144 tokens per batch on average. So thats almost 3x larger batches. I would expect that a V100 would be able to parallellize on larger batches but I may be wrong. If you think this is what the issue is then I am satisfied. :)

**Comment by lukaszkaiser** [comment]
I think it is, good to have clarified that :).
