### ISSUE TITLE
Support layer custom names

### ISSUE THREAD

**Issue by w4-sjcho** [google/trax#373]
### Description

It is extremely difficult to debug nested `Serial` layer's stack, especially when I'm using layers like `Branch` and `SerialWithSideOutputs` (the layers that are built from other basic combinators), because the error stack shows them as just `Serial` layer.

I've made some small changes to `base.Layer` and `combinators.py` so that `base.Layer` supports overriding layer names (`self.__class__.__name__`) with user supplied names, and it helped debugging large models a lot.

```python
# base.py
class Layer(object):
  def __init__(self, n_in=1, n_out=1, name=None):  # Added name
    self._name = name or self.__class__.__name__
    ...
# Replace self.__class__.__name__ in LayerError calls with self._name

# combinators.py
def Branch(*layers, name='Branch'):
  return Serial(..., name=name)
```

If this seems OK, I'd be glad to make a PR for this.

**Comment by lukaszkaiser** [comment]
Looks great, please send a PR!
