### ISSUE TITLE
Hallo，if possible，it is appreciate for your to upload a gin to train t2t_translate_ende_wmt32k with LSHSelfAttention.

### ISSUE THREAD

**Issue by zhangweisenHW** [google/trax#406]
### Description
Hallo，if possible，it is appreciate for your to upload a gin to train t2t_translate_ende_wmt32k with LSHSelfAttention. i have tried for many time ,but still return error.
...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
The Reformer config for WMT en-de is here:
https://github.com/google/trax/blob/master/trax/configs/reformer_wmt_ende.gin
