### ISSUE TITLE
[LSHSelfAttention] Why does q_start has to be of type int in incremental_forward_unbatched?

### ISSUE THREAD

**Issue by patrickvonplaten** [google/trax#462]
### Question: 
In line: https://github.com/google/trax/blob/e80206018f5a7ea4db1e83d5c9ec23cd58ec15f2/trax/layers/research/efficient_attention_v2.py#L1239

`q_start` is checked to be of type `int`. This means that if `q_start = DeviceArray(0, dtype=int32)` e.g. the code jumps directly into "handling one token at a time and it is checked that `q_len == 1`.

Removing the `isinstance(q_start, int)` line works fine if I want to handle more than one token at a time. 

What is this `isinstance` check good for?

**Comment by nkitaev** [comment]
If the code is being jitted and q_start is an abstract tensor object, the `q_start == 0` comparison can't be evaluated to a python boolean. The `isinstance(q_start, int)` check could also be replaced for checking that it's not an abstract tracer object used for jitting.
