### ISSUE TITLE
Is there any plan to merge with Flax?

### ISSUE THREAD

**Issue by epignatelli** [google/trax#472]
Apologies in advance for the question that might seem off topic.

Given the early breakout of JAX, it seems there is no convergence yet on an high level library for deep and reinforcement learning.

Do you personally have any plan to merge with [flax](https://github.com/google/flax)?
The question comes from the will to contribute efficiently to a these libraries, where efficiency the probability to be superseeded.

**Comment by lukaszkaiser** [comment]
I believe that Flax has a very different design and philosophy, so I don't see a merge soon (though everything can change of course).
