### ISSUE TITLE
[Bug] loss_fn argument for Trainer must not be a function since 1.2.4

### ISSUE THREAD

**Issue by stefan-falk** [google/trax#473]
### Description

As in previous examples shown, `loss_fn` should be callable like this:

```python
trainer = trax.supervised.Trainer(
    model=eval(train_model.selector),
    loss_fn=trax.layers.CrossEntropyLoss,
    optimizer=trax.optimizers.Adam,
    lr_schedule=trax.lr.MultifactorSchedule,
    inputs=trax.supervised.inputs.Inputs(train_stream),
    output_dir=output_dir,
)
```

However, since the latest upgrade to 1.2.4 this cannot not work anymore.

In the `trainer_lib` the `loss_fn` gets passed to a `Serial` constructor:

https://github.com/google/trax/blob/93f2bd47f5f17aacafe3f312ae56ce6f98d93ee7/trax/supervised/trainer_lib.py#L130

Which in turn runs `_ensure_flat` in it's constructor

https://github.com/google/trax/blob/5b1565910a53d0d1175f647cc67db48e334d8f90/trax/layers/combinators.py#L47

However, all objects in `layers` have to be of type `base.Laser`:

```python
def _ensure_flat(layers):
  """Ensures that layers is a single flat list of Layer instances."""
  if len(layers) == 1 and layers[0] is None:
    layers = ()
  else:
    layers = _deep_flatten(layers)
  for obj in layers:
    if not isinstance(obj, base.Layer):
      raise ValueError(
          f'Found nonlayer object ({obj}) in layers: {layers}')
  return layers
```

See

https://github.com/google/trax/blob/5b1565910a53d0d1175f647cc67db48e334d8f90/trax/layers/combinators.py#L775

Thus we'll see an exception:

```
ValueError: Found nonlayer object (<function CrossEntropyLoss at 0x7fc5be59a9e0>) in layers:
```

**Comment by afrozenator** [comment]
Let me look into this, but if possible can you send a repro? Is the problem in 1.2.4 or earlier?

**Comment by lukaszkaiser** [comment]
This was changed on purpose in 1.2.4 so as to make sure losses are indeed just layers. A quick fix here is just making it CrossEntropyLoss().

But let's think if the quick fix is enough. Stefan: do you have a use-case where having functions-creating-layers instead of layer instances is actually desireable?

**Comment by stefan-falk** [comment]
Hi! :) 

I only intended to point this out. E.g. is the naming `loss_fn` a bit misleading. Also the old examples are passing only the type `loss_fn=trax.layers.CrossEntropyLoss` instead of the object. 

@afrozenator The problem starts with 1.2.4 and it's easy to reproduce by just passing something that is not a layer to `loss_fn`

**Comment by lukaszkaiser** [comment]
Thanks for pointing this out! I agree the naming is now misleading - and sorry for the incompatibility! But if there's no reason to have function there, we should probably go with just having layers and maybe just calling it loss? Thanks for bringing this to our attention!

**Comment by stefan-falk** [comment]
You're welcome. No big deal - in cases like this exceptions are rather clear and one can figure out what to do :) Regarding the argument: I really know too little at this point about trax to be able to say what makes sense but one idea would be to do like Keras when compiling the model (see [docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model)):

> **Arguments:**
> - **loss:** String (name of objective function), objective function or tf.keras.losses.Loss instance. See tf.keras.losses. An objective function is any callable with the signature scalar_loss = fn(y_true, y_pred). If the model has multiple outputs, you can use a different loss on each output by passing a dictionary or a list of losses. The loss value that will be minimized by the model will then be the sum of all individual losses.

But of course that will make the implementation of `Trainer` a bit more complex. 

One advantage of functions could be that I can just provide a function in cases where I already have one in my code. Also I don't need to write a wrapper-object for such a function or any function which does not require data or a state during execution.

After all I would say this is a design question. We can always have a `trax.layers.LambdaLoss` as in `LambdaLoss(loss_fn=my_loss_fn)` to provide a simple wrapper.

> Thanks for bringing this to our attention!

I say thanks for sharing t2t and trax with us :)

**Comment by lukaszkaiser** [comment]
I think the way we're trying to go is `trax.layers.Fn('MyLoss', loss_fn)` - `Fn` is just `Lambda`. Thanks for your help as we try to make it understandable - we need to improve the docs too!

Closing for now as the immediate issue is resolved.
