### ISSUE TITLE
Tensor2Tensor Transformer is not Trax Transormer

### ISSUE THREAD

**Issue by DevKretov** [google/trax#493]
### Description

Hello. I've been playing around with both T2T and Trax libraries for a while. Since Trax has several bugs during inference, I've decided to switch to T2T. However, it seems to me that Transformer in Tensor2Tensor is not the same as in Trax. 

In Tensor2Tensor I create my Transformer model this way:

```
hparams_my = {
    'batch_size': 128,
    'batch_shuffle_size': 128,
    'use_fixed_batch_size': True,
    'num_hidden_layers': 1,
    'max_input_seq_length': 252,
    'max_target_seq_length': 252,
    'max_length': 252,
    'symbol_modality_num_shards': 1,
    'filter_size': 2048,
    'dropout': 0.1
}
```

In Trax:
```
Transformer(input_vocab_size=127,
                output_vocab_size=127,
                d_model=512,
                d_ff=2048,
                n_encoder_layers=1,
                n_decoder_layers=1,
                n_heads=8,
                dropout=0.1,
                max_len=2048,
                mode='train',
                ff_activation=tl.Relu):
```

After I run training with T2T, I get this message:
(btw, 2 times)
```
INFO:tensorflow:Trainable Variables Total size: 7433728
INFO:tensorflow:Trainable Variables Total size: 7433728
```

Whereas in Trax I after I call `trainer.print_n_weights()` I get
```
Step      0: Total number of trainable weights: 7614591
```

I would like to notice, that when I train my Transformer model in Trax, I reach convergence almost immediately (considering the nature of the task - just simple sequence copying with little changes), while with T2T I reach some loss values like 3-4 and no convergence at all. 

Could anybody tell me what do I have to do? It seems like a common problem with T2T Transformer convergence, but I want to emphasise that in Trax it is another Transformer...

**Comment by lukaszkaiser** [comment]
There are very many hparams that you can set for Transformer in T2T, and I believe there is a version that'll make it match Trax... but it's gotten really hard to find. Well - that's why we made Trax!

I feel like finding the exact hparams to match Trax may be quite a lot of work, so maybe instead we correct inference in Trax? What are the bugs?

**Comment by lukaszkaiser** [comment]
Hmm, it may also be that some dense layers in Trax have biases that we don't use in T2T?

**Comment by DevKretov** [comment]
> There are very many hparams that you can set for Transformer in T2T, and I believe there is a version that'll make it match Trax... but it's gotten really hard to find. Well - that's why we made Trax!
> 
> I feel like finding the exact hparams to match Trax may be quite a lot of work, so maybe instead we correct inference in Trax? What are the bugs?

The thing that blows my mind is that while training the same network with the same data and on a relatively easy task, my T2T transformer failes to converge compared to Trax's transformer, which learns very well and converges after several hundreds steps, which is the behaviour I expect, since my task is to mostly copy data and make some small changes to the missing diacritics.

One more thing worth mentioning is that the learning rate in both frameworks has different flows even when I fix all the T2T learning rate scheduler's parameters and set then equal to those Trax has. Take a look. This is Trax:

![Screenshot 2020-04-23 at 09 37 11](https://user-images.githubusercontent.com/38000417/80072246-43356880-8546-11ea-9363-f194fd5796aa.png)

And this is T2T:

![Screenshot 2020-04-23 at 09 39 31](https://user-images.githubusercontent.com/38000417/80072334-62cc9100-8546-11ea-801a-8c98bdf2ac64.png)

Also T2T Transformer has a huge variance in loss while being trained. Considering numerous issues in T2T regarding the same problem, it was my motivation to get it straight. 

Thank you for help.

**Comment by DevKretov** [comment]
> I feel like finding the exact hparams to match Trax may be quite a lot of work, so maybe instead we correct inference in Trax? What are the bugs?

I would really appreciate if we could fix these bugs in Trax. One thing that I've accomplished is inference, but in a weird way - I load my model with mode='train' and run inference by providing transformer with the whole input and the empty array as the currently decoded output. Then, I feed it back and get the next prediction. Basically, this process replicates the greedy beam search strategy with beam size 1, but still it seems to me, that it's very cumbersome and awkward way to do it.

One more thing I really want to get out from the model are the attention weights. I'll take a look at how to hack those basing on the strategy from T2T (fortunately, getting attention weights didn't have many complications).

**Comment by lukaszkaiser** [comment]
Ok: let's focus on repairing the bugs in Trax! What is the current inference bug? Could you open a separate Issue for that? I'll then close this one, so we can focus on the bugs one-by-one.

**Comment by DevKretov** [comment]
Well, I'll open some new issues tomorrow morning. Thanks.

**Comment by lukaszkaiser** [comment]
Thanks!
