### ISSUE TITLE
running reformer with multiple batches

### ISSUE THREAD

**Issue by alidi8677** [google/trax#515]
Very interesting and useful library! Thanks! My question is: How one arranges my_input function in order to run multiple batches using reformer. The text generation Colab only covers one batch. I got some useful information from configs (batch_fn) but still the arrangement of input is not clear. I have a sequence with 4M tokens and a 50000 vocabsize for a language model problem.

**Comment by alidi8677** [comment]
I managed to work around input function to yield batch_size data every time trainer.train_epoch calls it. Then the steps meaning is epochs / number of batches. It seems like it is working.However I'm not 100% sure if this is the right answer. There should be a more straight forward way.

**Comment by lukaszkaiser** [comment]
I hope the Trax intro colab / main README clarifies this now - you make a python iterator and pass it to TrainTask. Closing, please reopen if it's still unclear or something fails!
