### ISSUE TITLE
Anyway to disable jit for debugging purposes?

### ISSUE THREAD

**Issue by py4** [google/trax#530]
I'm editing the trax codebase and for debugging purposes I have to print values eagerly. But because of the jit, everything is a jit abstract expression(https://github.com/google/jax/issues/196). How do you guys debug the code without being able to print anything? I assume if i disable the jit, everything would be executed eagerly. Am i right? If yes, is there anyway to disable jit?

**Comment by pkol** [comment]
you may be interested in  https://github.com/google/jax/issues/252#issuecomment-461276665

There are two ways to achieve this with Trax:
1. easiest one is to set environment variable `JAX_DISABLE_JIT=1 `. For example run you training like this:
```
JAX_DISABLE_JIT=1 python -m trax.trainer --config_file=$PWD/trax/configs/mlp_mnist.gin
```

2. You may also set some gin options:
```
_jit_update_fn.jit=False
_jit_predict_fn.jit = False
_jit_compute_loss_fn.jit = False
_is_jit_init.value = False
```
You may reffer to `trax/supervised/trainer_lib.py` to see what each of those does.

**Comment by lukaszkaiser** [comment]
Yes: we also added a `trax.fastmath.disable_jit()` function to just make jit(f) = f, for other backends than jax.
