### ISSUE TITLE
Setting JAX_DISABLE_JIT still compiles beam_search to XLA

### ISSUE THREAD

**Issue by py4** [google/trax#616]
I'm training a Reformer model. For debugging purposes during beam search, i was doing some printings in attention module but because the code is compiled to XLA graph, my prints are not working. I tried to disable jit using setting `JAX_DISABLE_JIT` environment variable but it seems that the code is still compiled to XLA because of the warning message `W external/org_tensorflow/tensorflow/compiler/xla/service/hlo_pass_fix.h:49] Unexpectedly high number of iterations in HLO passes, exiting fixed point loop.` and the fact that my prints are not being printed.

**Comment by lukaszkaiser** [comment]
On head, we made sure disabling JIT in Trax also just does not call jit. But it's suspicious - are you sure it's not XLA invoked for single ops?
