### ISSUE TITLE
Trainer vs Loop+TrainTask+EvalTask

### ISSUE THREAD

**Issue by zack466** [google/trax#675]
### Question
What is point in having two different methods of training in Trax?

I notice that there is a Trainer class in `/supervised/trainer_lib.py`, but there are also training utilities in `/supervised/training.py`. Trainer appears to have more features (lr scheduler, checkpointing, history) but Loop, TrainTask, and EvalTask are a lot better documented.

Which one should be used for training models? Will either be superseded by the other in the near future?

**Comment by lukaszkaiser** [comment]
We are in the process of merging the two: cleaning up Trainer (like moving id_to_mask out) while expanding the functionality of Loop. It is taking time as we want to do it properly and keep all the functionality, but the goal is to have both have the same functions and just merge them.

I'll keep this issue open to track it. Please let us know if there are parts of the both APIs you like/dislike in particular, that'll help us merge them into a final state.

**Comment by zack466** [comment]
I like the Loop/Traintask/Evaltask API because it separates the model, training, and evaluation and is more clean. Meanwhile, the Trainer is just a large API call that can be difficult to debug. Looking at the code, it seems Loop now has most of the features of Trainer except for History and parallelization, so I don't really have much else to say.

On an unrelated note, it would probably be helpful to have a notebook explicitly walking through the training API so users don't have to dig through trax source code looking for examples/reference code (something similar to `/layers/intro.ipynb`.

**Comment by lukaszkaiser** [comment]
The main Trax intro notebook has been ported to Loop API and the Trainer API is deprecated now. It's still there, but hopefully we'll remove it soon. Please use Loop and let us know what's missing, we're moving everything to it.
