### ISSUE TITLE
ModuleNotFoundError: No module named 'trax.supervised.tf_inputs'

### ISSUE THREAD

**Issue by elliotthwang** [google/trax#725]
### Description

import trax.models
import trax.optimizers
import trax.supervised.tf_inputs
import trax.supervised.trainer_lib

### Environment information
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-d3f4fec4fba3> in <module>()
      1 import trax.models
      2 import trax.optimizers
----> 3 import trax.supervised.tf_inputs
      4 import trax.supervised.trainer_lib

ModuleNotFoundError: No module named 'trax.supervised.tf_inputs'
```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
Hi Elliot. It looks like you're using a new config file with an old version of Trax. Can it be? We're aiming to make a release soon, that should help!

**Comment by lukaszkaiser** [comment]
This should work with the new release so closing for now. Please reopen if the bug reappears of course!

**Comment by elliotthwang** [comment]
@lukaszkaiser  Thanks!  It's work.

**Comment by elliotthwang** [comment]
@lukaszkaiser  Thanks! It works now.
