### ISSUE TITLE
Gin config for Speech Recognition 

### ISSUE THREAD

**Issue by RegaliaXYZ** [google/trax#755]
It seems there isn't any .gin config file for Speech Recognition task. (And overall very little documentation on how to implement this task with Trax)

**Comment by lukaszkaiser** [comment]
Not yet, but hopefully soon! If you have some ASR training or colabs, please let us know - it's a TODO we're hoping to get to, but it may be a few weeks.

**Comment by lukaszkaiser** [comment]
Let's use the existing #439 issue to track this, I'll close this one.
