### ISSUE TITLE
Text Generation Notebook breaks on v1.2.4

### ISSUE THREAD

**Issue by elx42** [google/trax#759]
### Description

Hi, thanks for sharing your work! I tried to run the Text Generation Example notebook (https://colab.research.google.com/github/google/trax/blob/master/trax/models/reformer/text_generation.ipynb#scrollTo=yiPdBenoZwH6) example on my own machine and realised that there seems to be an issue when running it on the latest version v1.2.4. 

This can be reproduced when changing the following line in the Colab to the new version number.

!pip install --upgrade -q gin git+https://github.com/google/trax.git@v1.2.3
to
!pip install --upgrade -q gin git+https://github.com/google/trax.git@v1.2.4

I will use the former release version to learn about the library and how to properly use Trax for training, applying a model etc. Probably, I'll figure out then by myself how to modify the calls to be compliant with the 1.2.4 release, but I think it would be great if these notebooks would work by default on the latest releases. 

Thanks again!

Matthias

### Environment information

```
OS: <your answer here>

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by lukaszkaiser** [comment]
Indeed - the Reformer notebooks are pinned to a specific version as we did not have enough cycles to keep them up-to-date all the time. We will update them all to 1.3.X at some point. Closing this for now though, as it is intended to work on 1.2.3.
