### ISSUE TITLE
Question/Potential Issue - Attention mask in SelfAttention Layer

### ISSUE THREAD

**Issue by patrickvonplaten** [google/trax#820]
### Description

It seems to me that it is not possible to mask the first position of a tensor when using the 
layer `SelfAttention`. Looking at this line:
https://github.com/google/trax/blob/e5631ed1c6043308be086f250b81e1a66bcd4219/trax/layers/research/efficient_attention.py#L1014 

and having let's say a mask tensor of shape (128,) (assuming masked=True, n_chunks_before=0, n_chunks_after=0) where as the token at the first position is set to 0 (masked) then the first token of the mask as further defined in line:
https://github.com/google/trax/blob/e5631ed1c6043308be086f250b81e1a66bcd4219/trax/layers/research/efficient_attention.py#L94
cannot be padded.

It can be seen that no mask is applied to the first position because "-0" is **not** less than 0 and so the first position is not padded. Note that this only applies for the very first token position. Is this expected or should the first token be masked as well?

### Environment information

```
OS: Linux / Ubuntu 

$ pip freeze | grep tensor
mesh-tensorflow==0.1.16
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-datasets==3.1.0
tensorflow-estimator==2.2.0
tensorflow-metadata==0.22.2
tensorflow-text==2.2.1


$ pip freeze | grep jax
jax==0.1.72
jaxlib==0.1.51

$ python -V
Python 3.7.5

```

### For bugs: reproduction and error logs

# Steps to reproduce:
```python
#!/usr/bin/env python3
from trax import shapes
from trax.layers import SelfAttention
import numpy as onp

self_attention = SelfAttention(n_heads=1, d_qk=64, d_v=64, masked=True, mode='eval', use_reference_code=True)

shape = (1, 128, 64)  # hidden states of BS = 1, SEQ_LEN = 128, HIDDEN_SIZE = 64
onp_input = onp.random.rand(*shape)
mask = onp.ones(shape[:-1], dtype=onp.int32)
mask[:, :10] = 0  # mask first ten tokens

input_sig = shapes.signature([onp_input, mask])
weights, state = self_attention.init(input_sig)

out = self_attention([onp_input, mask], weights=weights, state=state)
```

=> print out mask of line: https://github.com/google/trax/blob/e5631ed1c6043308be086f250b81e1a66bcd4219/trax/layers/research/efficient_attention.py#L94

gives:

```
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]]
```

=> I would have expeced it to give:

```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]]
```

(see difference at first position).

**Comment by afrozenator** [comment]
Thanks for reporting this @patrickvonplaten - while you are right that this is a bug and it doesn't allow an arbitrary mask, but in practice this isn't an issue since mask at position 0 is almost always 1, i.e. masks usually look like [1, 1, 1, 1, 0, 0, 0, 0,]. The mask at https://github.com/google/trax/blob/e5631ed1c6043308be086f250b81e1a66bcd4219/trax/layers/research/efficient_attention.py#L94 should be the inverse of the input mask (approximately).

I have a PR out fixing this though feel free to look at it and leave a comment if you like.

Again, thanks for reporting this.

**Comment by lukaszkaiser** [comment]
Looks like it's been resolved in the PR above. Thanks again for reporting @patrickvonplaten and please re-open if anything like this resurfaces!
