### ISSUE TITLE
Configurable 'train' doesn't have a parameter named 'use_loop'

### ISSUE THREAD

**Issue by ElhamSol** [google/trax#874]
### Description

I trained the reformer model locally with version 1.3.1 and the config file: "reformer_wmt_ende".

When I'm trying to use it for inference in the colab:
https://colab.research.google.com/github/google/trax/blob/master/trax/models/reformer/machine_translation.ipynb#scrollTo=psnUF-8c02o_

I get an error 
`Configurable 'train' doesn't have a parameter named 'use_loop'`

![image](https://user-images.githubusercontent.com/63062486/88313389-7b814a00-cce1-11ea-8331-90f80bf6f50b.png)

Could you help me resolve it please?

**Comment by lukaszkaiser** [comment]
The colab you're using is pinned to pip-install Trax 1.2.3, an old version -- while the gin config you're trying to open comes from a recent Trax version, so it doesn't work in 1.2.3.

If you just want to run a translation model, please look at the main README and the new Trax intro colab, which has an example translating English to German. We will update the Reformer colabs in time, for now they are set to older trax versions as we did not have enough time to update them yet (and want to keep them working).

**Comment by ElhamSol** [comment]
Well, the colab I worked on was set to 1.3.1 and I also trained locally on 1.3.1.
But, for now I'm checking the new version 1.3.3 and the new intro colab which is btw much more informative than the previous version. So thank you for that.
I'll try to get it work learning from this new colab.
