### ISSUE TITLE
'int' object has no attribute 'split' In call to configurable 'multifactor'

### ISSUE THREAD

**Issue by ElhamSol** [google/trax#878]
### Description

I am trying to train the reformer model in colab with version 1.3.1 based on the config file: "reformer_wmt_ende".

But, the training fails due to this error:

![image](https://user-images.githubusercontent.com/63062486/88405420-3b7f9d00-cd9d-11ea-8abd-a0c32f57a18c.png)

The link to the colab is here:
https://colab.research.google.com/drive/1VwJPKaE6L633xgwoGRaTQi4XSBo74Esk?usp=sharing

Any help is much appreciated!

**Comment by lukaszkaiser** [comment]
Unluckily I don't have access to the above colab, so I cannot tell for sure. But it looks like parameters of multifactor are mis-matched, an int is appearing where a string should appear. Maybe use named parameters when calling multifactor? Closing for now, feel free to reopen if the problem persists.
