### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by harshil15999** [google/trax#915]
###  Could you please provide the link to the documentation of this library?

...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep trax
# your output here

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by sanjibnarzary** [comment]
This link may help [Trax Documentation](https://trax-ml.readthedocs.io/en/latest/). It is mentioned in readme as well.

**Comment by lukaszkaiser** [comment]
Yes: it's under https://trax-ml.readthedocs.io/en/latest/
