### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by Nishant-Pall** [google/trax#982]
Hi, is there gonna be any release soon which has support for windows?

**Comment by lukaszkaiser** [comment]
I think the current one should be working fine as long as you use WSL - it's still Windows, but linux under the hood:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

As for native support, we asked on JAXers and they're working on it. Are there reasons you'd prefer to not use WSL? Please consider opening an issue with JAX too - this may help them prioritize! (There's nothing OS specific in Trax - it's just the dependencies...)

**Comment by Nishant-Pall** [comment]
Okay, I will go through there as well, thanks a lot for the response!!
