### ISSUE TITLE
I still don't really understand the  tl.Residual in trax. The doc is not really clear on how it works

### ISSUE THREAD

**Issue by JonathanSum** [google/trax#985]
### Description
I still don't really understand the  tl.Residual in trax. The doc is not really clear on what it is.
...

### Environment information

```
OS: <Window 10 or colab's linux>

Do have any tutorials about it? I tried to watch its source code. I don't understand things like Branch and see a lot of to-dos over there.
The doc about it is not really clear about it. Thus, do we have an example of it? I came from Pytorch. They teach about it like x +conv(x). But comparing to Trax, it is very confusing.

**Comment by zack466** [comment]
You might want to look at the trax layers intro [here](https://trax-ml.readthedocs.io/en/latest/notebooks/layers_intro.html#Layers-combine-into-layers.). It talks about combinators, including how branch/residual can be used.

**Comment by JonathanSum** [comment]
@zack466  Thank you.
